# Generated by Django 3.1.13 on 2021-12-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField()),
                ('category_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.IntegerField()),
                ('subcategory_name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='crehana_store.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=254)),
                ('level', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('course_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('users', models.IntegerField()),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='crehana_store.category')),
                ('subcategory', models.ForeignKey(db_column='subcategory', on_delete=django.db.models.deletion.CASCADE, to='crehana_store.subcategory')),
            ],
        ),
    ]
