# Generated by Django 3.1.13 on 2021-12-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crehana_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
    ]
